const Data = [
    {  
      image: "images/GDSC.png",
      name: "GDSC",
      category: "Technical",
      img: "images/Linkedin-icon.png", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/gdscbvp/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
      },
  
    {
      image: "images/MLSAC.png",
      name: "MLSAC",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/mlsacbvp/mycompany/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/mlsac_bvcoe/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",

      },

    {
      image: "images/MLSAC.png",
      name: "BMS",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/blissful-minds-society/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/blissfulminds_bvcoe/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
  
    {
      image: "images/MLSAC.png",
      name: "QAAFILA",
      category: "Cultural",
      img: "images/Linkedin-icon.png", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/qaafila_bvp/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "ZAAHIR",
      category: "Cultural",
      img: "images/Linkedin-icon.png", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/zaahir.bvcoe/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "EDC",
      category: "Cells",
      img: "images/Linkedin-icon.png",
      link1: 'https://www.linkedin.com/company/bvp-edc/mycompany/', 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/bvpedc/",
      site: "images/Link-icon.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "NIDUS",
      category: "Cells",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/bvp-nidus/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/bvp_nidus/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "ISTE",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/in/bvp-iste-89529a218/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/bvpiste/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "ACM",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/acmbvp/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/acm_bvp/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "EduMinerva",
      category: "Non-Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/eduminerva/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/edu_minerva/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "Optica",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/bvp-optica/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/bvpoptica/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
      image: "images/MLSAC.png",
      name: "IEEE",
      category: "Technical",
      img: "images/Linkedin-icon.png",
      link1: "https://www.linkedin.com/company/bvp-ieee/", 
      insta: "images/Instagram-icon.jpg",
      link2: "https://www.instagram.com/bvpieee/",
      site: "images/Link-icon.jpg",
      link: 'https://www.youtube.com/',
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        image: "images/MLSAC.png",
        name: "Tech Shuttle",
        category: "Technical",
        img: "images/Linkedin-icon.png",
        link1: "https://www.linkedin.com/company/techshuttle-hack-club-bvp/", 
        insta: "images/Instagram-icon.jpg",
        link2: "https://www.instagram.com/bvphackclub/",
        site: "images/Link-icon.jpg",
        link: 'https://www.youtube.com/',
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
      },
      {
        image: "images/MLSAC.png",
        name: "ISA",
        category: "Technical",
        img: "images/Linkedin-icon.png",
        link1: "https://www.linkedin.com/company/isa-bvp/", 
        insta: "images/Instagram-icon.jpg",
        link2: "https://www.instagram.com/isa.bvp/",
        site: "images/Link-icon.jpg",
        link: 'https://www.youtube.com/',
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
      },
      {
        image: "images/MLSAC.png",
        name: "CSI",
        category: "Technical",
        img: "images/Linkedin-icon.png",
        link1: "https://www.linkedin.com/company/bvpcsi-qal/", 
        insta: "images/Instagram-icon.jpg",
        link2: "https://www.instagram.com/bvpcsi/",
        site: "images/Link-icon.jpg",
        link: 'https://www.youtube.com/',
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
      },
      {
        image: "images/MLSAC.png",
        name: "Campus Blocks",
        category: "Technical",
        img: "images/Linkedin-icon.png",
        link1: "https://www.linkedin.com/company/bvp-ieee/", 
        insta: "images/Instagram-icon.jpg",
        link2: "https://www.instagram.com/campusblocksbvp/",
        site: "images/Link-icon.jpg",
        link: 'https://www.youtube.com/',
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
      },
];
  
  export default Data;